# Market Master - Simplified Kubernetes Deployment (No Persistent Volumes)

apiVersion: v1
kind: Namespace
metadata:
  name: market-master
  labels:
    name: market-master
    environment: production

---
# ConfigMap for application configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: market-master-config
  namespace: market-master
data:
  MLFLOW_TRACKING_URI: "http://mlflow-service:5000"
  MLFLOW_REGISTRY_URI: "http://mlflow-service:5000"
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "production"

---
# Secret for sensitive data
apiVersion: v1
kind: Secret
metadata:
  name: market-master-secrets
  namespace: market-master
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  DB_PASSWORD: "bWFya2V0X21hc3Rlcl9wYXNzd29yZA=="  # market_master_password
  REDIS_PASSWORD: "cmVkaXNfcGFzc3dvcmQ="  # redis_password

---
# Service Account for the application
apiVersion: v1
kind: ServiceAccount
metadata:
  name: market-master-sa
  namespace: market-master
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/market-master-eks-node-group-role

---
# Deployment for Market Master Application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-master-app
  namespace: market-master
  labels:
    app: market-master
    component: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-master
      component: app
  template:
    metadata:
      labels:
        app: market-master
        component: app
    spec:
      serviceAccountName: market-master-sa
      containers:
      - name: market-master
        image: market-master:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
          name: http
        - containerPort: 5000
          name: mlflow
        env:
        - name: MLFLOW_TRACKING_URI
          valueFrom:
            configMapKeyRef:
              name: market-master-config
              key: MLFLOW_TRACKING_URI
        - name: MLFLOW_REGISTRY_URI
          valueFrom:
            configMapKeyRef:
              name: market-master-config
              key: MLFLOW_REGISTRY_URI
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: market-master-config
              key: LOG_LEVEL
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: market-master-config
              key: ENVIRONMENT
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: market-master-secrets
              key: DB_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: market-master-secrets
              key: REDIS_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

---
# Service for Market Master Application
apiVersion: v1
kind: Service
metadata:
  name: market-master-service
  namespace: market-master
  labels:
    app: market-master
    component: app
spec:
  type: ClusterIP
  ports:
  - port: 8501
    targetPort: 8501
    protocol: TCP
    name: http
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: mlflow
  selector:
    app: market-master
    component: app

---
# MLflow Service
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: market-master
  labels:
    app: market-master
    component: mlflow
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: mlflow
  selector:
    app: market-master
    component: mlflow

---
# MLflow Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
  namespace: market-master
  labels:
    app: market-master
    component: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-master
      component: mlflow
  template:
    metadata:
      labels:
        app: market-master
        component: mlflow
    spec:
      containers:
      - name: mlflow
        image: python:3.9-slim
        command: ["/bin/bash"]
        args:
        - -c
        - |
          pip install mlflow
          mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db
        ports:
        - containerPort: 5000
          name: mlflow
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"

---
# LoadBalancer Service for external access
apiVersion: v1
kind: Service
metadata:
  name: market-master-lb
  namespace: market-master
  labels:
    app: market-master
    component: app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8501
    protocol: TCP
    name: http
  selector:
    app: market-master
    component: app 