global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'market-master-app'
    static_configs:
      - targets: ['market-master-app:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'mlflow'
    static_configs:
      - targets: ['market-master-mlflow:5000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'grafana'
    static_configs:
      - targets: ['market-master-grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s 